export const GET_WORD_CATEGORIES = 'GET_WORD_CATEGORIES';
export const WORD_CATEGORIES_LOADING = 'WORD_CATEGORIES_LOADING';

export const ADD_WORD_CATEGORY_TO_USER = 'ADD_WORD_CATEGORY_TO_USER';
export const REMOVE_WORD_CATEGORY_FROM_USER = 'REMOVE_WORD_CATEGORY_FROM_USER';
