export const GET_WORD_CATEGORIES = 'GET_WORD_CATEGORIES';
export const WORD_CATEGORIES_LOADING = 'WORD_CATEGORIES_LOADING';

export const ADD_WORD_CATEGORY_TO_USER = 'ADD_WORD_CATEGORY_TO_USER';
export const REMOVE_WORD_CATEGORY_FROM_USER = 'REMOVE_WORD_CATEGORY_FROM_USER';

export const USER_LOADING = 'USER_LOADING';
export const USER_LOADED = 'USER_LOADED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAIL = 'LOGIN_FAIL';
export const LOGOUT_SUCCESS = 'LOGOUT_SUCCESS';
export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';
export const REGISTER_FAIL = 'REGISTER_FAIL';
export const GET_ERRORS = 'GET_ERRORS';
export const CLEAR_ERRORS = 'CLEAR_ERRORS';